opensciencegrid/osg-vo-config

bin/vomses-crosscheck
For SOFTWARE-2445. The `vomses-crosscheck` script now needs to handle cases where a single VOMS server has multiple DNs. These look like additional pairs of DN and CA in the .lsc file. For each entry in the vomses file, ensure that at least one of the DN and CA pairs in the corresponding .lsc file matches.
Detect malformed .lsc files - these are files with an odd number of lines, which are missing one half of the pair.
Limitation: it is possible to have extra pairs in an .lsc file that have no corresponding vomses entries. This is currently not detected.
=> Handle .lsc files with multiple pairs of DNs and CAs

bin/vomses-crosscheck, vomsdir/miniclean/voms.hep.pnnl.gov.lsc, vomsdir/project8/voms.hep.pnnl.gov.lsc, vomses
It didn't work as intended with multiple voms certs in a single lsc file.
Also back out the related changes to support this from vomses-crosscheck.
=> remove multi-cert lsc files

gums.config.template
drop vomsUserGroup:
- cdf-cnaf         (vomsServer: cdf1)
- cdfdev-cnaf      (vomsServer: cdf1)
- cdffgrid-cnaf    (vomsServer: cdf1)
- cdfnam-cnaf      (vomsServer: cdf1)
- cdftestcaf-cnaf  (vomsServer: cdf1)
- cdf-pd           (vomsServer: cdf)
- cdfdev-pd        (vomsServer: cdf)
- cdffgrid-pd      (vomsServer: cdf)
- cdfnam-pd        (vomsServer: cdf)
- cdftestcaf-pd    (vomsServer: cdf)
drop groupToAccountMapping:
- cdf-cnaf
- cdf-pd
- cdfdev-cnaf
- cdfdev-pd
- cdffgrid-cnaf
- cdffgrid-pd
- cdfnam-cnaf
- cdfnam-pd
- cdftestcaf-cnaf
- cdftestcaf-pd
drop hostToGroupMapping:
- cdf-cnaf
- cdfdev-cnaf
- cdffgrid-cnaf
- cdfnam-cnaf
- cdftestcaf-cnaf
- cdf-pd
- cdfdev-pd
- cdffgrid-pd
- cdfnam-pd
- cdftestcaf-pd
=> drop dependent objects from cdf, cdf1 vomsServers (SOFTWARE-2612)

bin/mk-vo-client-tarball
This is just the script that I use for generating the vo-client-NN-osg.tar.gz upstream source tarballs.
It now calls the script to generate the voms-mapfile-default from SOFTWARE-2609.
=> script to generate upstream osg tarball

gums.config.template
For well over a year, LIGO has exclusively utilized `/osg/ligo`; their VOMS server has been offline for much longer.
=> Remove dead LIGO server from GUMS template

gums.config.template
Previously, the USATLAS mapping matched on `vo` - meaning that *anyone* in ATLAS would match the USATLAS rules.  This changes the matching rule to `vogroup`, meaning only those in the `/atlas/usatlas` group matches.
This commit also cleans up the group naming; after about a decade, we can just call it `atlas` and no longer `newAtlas`.
=> Correct USATLAS mapping

edg-mkgridmap.config
Apparently the lcluser fields were accidentally omitted when `project8` & `miniclean` were added.
=> add lcluser field for project8 & miniclean (SOFTWARE-2727)

bin/manual-mapfile-from-gumsdb.py
I've been asked to have the manual-mapfile-from-gumsdb.py script generate separate map files rather than dump everything to stdout.
New output:
```
root@el6-gumsx ~ # ./manual-mapfile-from-gumsdb.py 
Writing ban-mapfile ...
Writing grid-mapfile ...
Writing voms-mapfile ...
root@el6-gumsx ~ # cat ban-mapfile
"/DC=org/DC=opensciencegrid/O=Open Science Grid/OU=People/CN=Alpha Flight 7727"
"/DC=org/DC=opensciencegrid/O=Open Science Grid/OU=People/CN=Dancing Zorba 4528"
"/DC=org/DC=opensciencegrid/O=Open Science Grid/OU=People/CN=Freddie Redonschnider 1234"
root@el6-gumsx ~ # cat grid-mapfile
"/DC=com/DC=example/OU=People/CN=Example User 12345" test
"/DC=org/DC=doegrids/OU=People/CN=Janet Doe 123456" osg
"/DC=org/DC=doegrids/OU=People/CN=Jane Doe 12345" osg …
```
=> generate separate map files rather than dump to stdout

vomsdir/osg/voms.opensciencegrid.org.lsc, vomses
(Note that the port is a lie, since this new VOMS server will never exist.)
=> add new InCommon DN/CA for voms.opensciencegrid.org (SOFTWARE-3248)

bin/gen-grid-vorolemap
It's either this or make a new script to generate the whole thing, which I was tempted to do, but stripping out just `/*` and `/Capability=...` is easy enough to add to this converter.
=> drop '/*' and '/Capability=...' for grid-vorolemap (SOFTWARE-3222)

edg-mkgridmap.config, gums.config.template, vomsdir/CIGI/vm246.roger.ncsa.illinois.edu.lsc, vomses
They no longer use the OSG; the VOMS cert is expired
=> Retire the CIGI VO (SOFTWARE-3598)

vomsdir/hcc/hcc-voms2.unl.edu.lsc, vomses
Note that the port is bogus, as it's not actually a VOMS host
=> add new hcc cert (SOFTWARE-3608)

voms-mapfile-default, vomsdir/nanohub/voms.nanohub.org.lsc, vomses
There was a miscommunication and we removed nanohub from the VO client
=> Adding nanohub back to the VO client (SOFTWARE-3706)

bin/vomses-crosscheck
We were using this script in our CI tests but it wasn't reporting errors in the exit status.
=> report error status in vomses-crosscheck

vomsdir/GLOW/glow-voms.cs.wisc.edu.lsc, vomses
It was issued by the OSG CA so it's no longer valid.
=> Drop stale GLOW cert

vomsdir/Gluex/gluex.phys.uconn.edu.lsc, vomses
We should have been done this together with gryphn since gluex is already using the new cert:
```console
openssl s_client -showcerts -servername gluex.phys.uconn.edu -connect gluex.phys.uconn.edu:15014 </dev/null
Server certificate
subject=/DC=org/DC=incommon/C=US/ST=Connecticut/L=Storrs/O=University of Connecticut/OU=Academic IT/CN=gluex.phys.uconn.edu
issuer=/C=US/O=Internet2/OU=InCommon/CN=InCommon IGTF Server CA
```
=> updating the cert of gluex

vomsdir/clas12/clas12.voms2.opensciencegrid.org.lsc, vomsdir/eic/eic.voms2.opensciencegrid.org.lsc, vomses
For SOFTWARE-5176, this adds the following hosts:
- fejlab.svc.opensciencegrid.org
- clas12.voms2.opensciencegrid.org
- eic.voms2.opensciencegrid.org
Note: I had to guess the port for all of these, and I guessed the VO name for fejlab.  (Don't know if this is correct!)
=> add new hosts for eic/clas12 (SOFTWARE-5176)

vomsdir/GLOW/voms.chtc.wisc.edu.lsc, vomsdir/clas12/clas12.voms2.opensciencegrid.org.lsc, vomsdir/eic/eic.voms2.opensciencegrid.org.lsc, vomses
Updated the certs for the currently unused CNs ("`voms2`" for EIC/CLAS12, "`voms`" for GLOW). Subjects and issuers have changed.
=> SOFTWARE-5743 Update EIC, CLAS12, and GLOW DNs and Issuers

vomsdir/osg/voms.opensciencegrid.org.lsc
Issuer went from `/C=US/O=Internet2/OU=InCommon/CN=InCommon IGTF Server CA` to `/C=US/O=Internet2/CN=InCommon RSA IGTF Server CA 3`
=> SOFTWARE-5832 Update voms.opensciencegrid.org.lsc issuer

rpm/vo-client.spec
For the above host, only include voms-*-auth.app.cern.ch in vomses. Include voms2.cern.ch, lcg-voms2.cern.ch, and voms-*-auth.cern.ch in vomsdir/
=> SOFTWARE-5861: Update vomses for atlas, alice, lhcb, and cms

rpm/vo-client.spec
Also remove dead code and use some macros.
=> Don't include new IAM service vomses entry for CMS (SOFTWARE-6060)
