edg-mkgridmap.config
per request in https://ticket.grid.iu.edu/32314 removing mcdrd vo
=> removed mcdrd vo

gums.template
remove mcdrd per request https://ticket.grid.iu.edu/32314
=> remove mcdrd

edg-mkgridmap.config, gums.config.template, vomsdir/CSIU/voms.grid.iu.edu.lsc, vomsdir/osg/voms.grid.iu.edu.lsc, vomsdir/osgedu/voms.grid.iu.edu.lsc, vomses
- Drop OSGEDU, CSIU
- Add voms.grid.iu.edu voms server for OSG
https://ticket.opensciencegrid.org/33040
https://jira.opensciencegrid.org/browse/SOFTWARE-2643
=> VO Package 72 updates

gums.config.template
Per https://ticket.opensciencegrid.org/33395
=> Remove unused CDF glidecaf settings

edg-mkgridmap.config
Changing CDF Entry to match vomses file per some info from Joe Boyd. I took out voms.fnal.gov and added voms1 and voms2.
=> Changing CDF Entry

gums.config.template
This has some fixups superseding #16
=> Update default CMS mappings (SOFTWARE-2691)

gums.config.template
Suggested mappings are taken from existing sites and desired CMS configurations.
=> Update default CMS mappings. SOFTWARE-2691

gums.config.template
Updates per:
https://jira.opensciencegrid.org/browse/SOFTWARE-2690
https://ticket.opensciencegrid.org/33395#1491839472
=> Update default Fermilab / FIFE mappings (SOFTWARE-2690)

edg-mkgridmap.config, gums.config.template, vomsdir/CIGI/vm246.roger.ncsa.illinois.edu.lsc, vomsdir/CIGI/voms.cigi.uiuc.edu.lsc, vomses
https://ticket.grid.iu.edu/33374
=> new VOMS server for CIGI (SOFTWARE-2712)

edg-mkgridmap.config, gums.config.template, vomsdir/auger/voms1.egee.cesnet.cz.lsc, vomses
Note: this was the only VOMS server for the auger VO.
https://jira.opensciencegrid.org/browse/SOFTWARE-3042
https://ticket.opensciencegrid.org/35501
https://ggus.eu/index.php?mode=ticket_info&ticket_id=131671
=> remove voms1.egee.cesnet.cz VOMS server (SOFTWARE-3042)

bin/gen-voms-mapfile, bin/manual-mapfile-from-gumsdb.py
=> script for generating voms-lcmaps mapfile for manual user groups

vomsdir/dteam/voms2.hellasgrid.gr.lsc, vomses
https://operations-portal.egi.eu/vo/view/voname/dteam
https://support.opensciencegrid.org/helpdesk/tickets/7614
=> Add VO configuration for dteam VO (SOFTWARE-3426)

Makefile
I plan to use this in the rpm spec, to modernize the build process.
=> add simple Makefile for generated mapfiles (SOFTWARE-3542)

vomsdir/lz/voms.hep.wisc.edu.lsc, vomses
https://opensciencegrid.atlassian.net/browse/SOFTWARE-3635
=> Update voms.hep.wisc.edu lz VO certificate (SOFTWARE-3635)

vomsdir/star/vo.racf.bnl.gov.lsc, vomses
https://support.opensciencegrid.org/a/tickets/8364
=> update cert dn/ca for star/vo.racf.bnl.gov (SOFTWARE-3692)

voms-mapfile-default, vomsdir/sphenix/hcvoms.sdcc.bnl.gov.lsc, vomses
=> Add sphenix vo (SOFTWARE-3718)

vomsdir/hcc/hcc-voms2.unl.edu.lsc, vomses
Certificate's DN changed from ST=NE to ST=Nebraska
=> Updated HCC voms cert

vomsdir/virgo/voms.cnaf.infn.it.lsc, vomses
The VIRGO VOMS already changed certificate. So we need to get this out very fast.
=> Updating the VIRGO voms certificate

vomsdir/wlcg/wlcg-voms.cloud.cnaf.infn.it.lsc, vomses
=> Update lsc file for the WLCG VO  (SOFTWARE-4331)

vomsdir/enmr.eu/voms-02.pd.infn.it.lsc, vomsdir/enmr.eu/voms2.cnaf.infn.it.lsc, vomses
https://support.opensciencegrid.org/a/tickets/66933
=> update enmr.eu vomses/lsc entires (SOFTWARE-4527)

rpm/vo-client.spec
feels like about time, doesn't it?
=> import vo-client.spec from osg packaging (SOFTWARE-5176)

rpm/vo-client.spec
https://opensciencegrid.atlassian.net/browse/SOFTWARE-5327
=> SOFTWARE-5327 Version bump and changelog

rpm/vo-client.spec
=> bump rpm version & changelog (SOFTWARE-5369)

vomsdir/clas12/clas12.voms.opensciencegrid.org.lsc, vomsdir/eic/eic.voms.opensciencegrid.org.lsc, vomses
=> New DNs for CLAS12 and EIC VOMS servers

.github/workflows/test-data-validation-scripts.yml, .github/workflows/validate-data.yml
Fix deprecated Node.js 12 actions with update to Node.js 16
=> Fix GHA deprecation warnings (Software-5354)

vomsdir/des/voms1.fnal.gov.lsc, vomsdir/dune/voms1.fnal.gov.lsc, vomsdir/fermilab/voms1.fnal.gov.lsc
@StevenCTimm how does this look to you for the first vo-client release?
=> Update voms1.fnal.gov to InCommon IGTF CA 3 (SOFTWARE-5743)

bin/vomses-crosscheck, rpm/vo-client.spec, vomses
we previously used that method for SOFTWARE-4595; I'd rather not have
two separate methods for doing the same thing.
=> Add entries to vomses file for SOFTWARE-5843 but remove them in the spec file

rpm/vo-client.spec
https://opensciencegrid.atlassian.net/browse/SOFTWARE-6060, though originally from https://opensciencegrid.atlassian.net/browse/SOFTWARE-5843
=> Flip the switch on shipping the new IAM-based VOMS endpoints
